[General]
import = ["~/.config/alacritty/themes/themes/blood_moon.toml"]
live_config_reload = true
shell = "/bin/bash"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = true
option_as_alt = "Both"

[scrolling]
history = 1000
mulitplier = 3

[font]
normal.family = "Terminus"
size = 15

[terminal]
osc52 = "CopyPaste"
